require("config.set")
require("config.keymap")
require("config.luasnip")
require("config.cmp")
require("config.lsp")
require("config.styling")
require("config.catppuccin").setup()
require("config.nvim-colorizer").setup()
require("config.bufferline").setup()
print('Init config loading')
