require("config.lazy")
require("config.set")
require("config.keymaps")
require("config.lsp")
-- require("config.luasnip")
-- require("config.cmp")
-- require("config.dap").setup()
-- require("config.other").setup()
-- require("config.navbuddy").setup()
-- require("config.neotree").setup()
-- require("config.oil").setup()
-- require("config.telescope")
-- require("config.obsidian").setup()
-- require("config.treesitter").setup()
-- require("config.dapui").setup()
